/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package run.acloud.commons.client.harbor.v1.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;


@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-08T09:10:54.107Z")
public class AccessLog {
  @SerializedName("log_id")
  private Integer logId = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("repo_name")
  private String repoName = null;

  @SerializedName("repo_tag")
  private String repoTag = null;

  @SerializedName("operation")
  private String operation = null;

  @SerializedName("op_time")
  private String opTime = null;

  public AccessLog logId(Integer logId) {
    this.logId = logId;
    return this;
  }


  @Schema(description = "The ID of the log entry.")
  public Integer getLogId() {
    return logId;
  }

  public void setLogId(Integer logId) {
    this.logId = logId;
  }

  public AccessLog username(String username) {
    this.username = username;
    return this;
  }


  @Schema(description = "Username of the user in this log entry.")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public AccessLog repoName(String repoName) {
    this.repoName = repoName;
    return this;
  }


  @Schema(description = "Name of the repository in this log entry.")
  public String getRepoName() {
    return repoName;
  }

  public void setRepoName(String repoName) {
    this.repoName = repoName;
  }

  public AccessLog repoTag(String repoTag) {
    this.repoTag = repoTag;
    return this;
  }


  @Schema(description = "Tag of the repository in this log entry.")
  public String getRepoTag() {
    return repoTag;
  }

  public void setRepoTag(String repoTag) {
    this.repoTag = repoTag;
  }

  public AccessLog operation(String operation) {
    this.operation = operation;
    return this;
  }


  @Schema(description = "The operation against the repository in this log entry.")
  public String getOperation() {
    return operation;
  }

  public void setOperation(String operation) {
    this.operation = operation;
  }

  public AccessLog opTime(String opTime) {
    this.opTime = opTime;
    return this;
  }


  @Schema(description = "The time when this operation is triggered.")
  public String getOpTime() {
    return opTime;
  }

  public void setOpTime(String opTime) {
    this.opTime = opTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessLog accessLog = (AccessLog) o;
    return Objects.equals(this.logId, accessLog.logId) &&
        Objects.equals(this.username, accessLog.username) &&
        Objects.equals(this.repoName, accessLog.repoName) &&
        Objects.equals(this.repoTag, accessLog.repoTag) &&
        Objects.equals(this.operation, accessLog.operation) &&
        Objects.equals(this.opTime, accessLog.opTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logId, username, repoName, repoTag, operation, opTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessLog {\n");
    
    sb.append("    logId: ").append(toIndentedString(logId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    repoName: ").append(toIndentedString(repoName)).append("\n");
    sb.append("    repoTag: ").append(toIndentedString(repoTag)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    opTime: ").append(toIndentedString(opTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }


  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

