/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package run.acloud.commons.client.harbor.v1.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;


@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-08T09:10:54.107Z")
public class ImmutableTagRule {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("project_id")
  private Long projectId = null;

  @SerializedName("tag_filter")
  private String tagFilter = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  public ImmutableTagRule id(Long id) {
    this.id = id;
    return this;
  }


  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ImmutableTagRule projectId(Long projectId) {
    this.projectId = projectId;
    return this;
  }


  @Schema(description = "")
  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }

  public ImmutableTagRule tagFilter(String tagFilter) {
    this.tagFilter = tagFilter;
    return this;
  }


  @Schema(description = "")
  public String getTagFilter() {
    return tagFilter;
  }

  public void setTagFilter(String tagFilter) {
    this.tagFilter = tagFilter;
  }

  public ImmutableTagRule enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }


  @Schema(description = "")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImmutableTagRule immutableTagRule = (ImmutableTagRule) o;
    return Objects.equals(this.id, immutableTagRule.id) &&
        Objects.equals(this.projectId, immutableTagRule.projectId) &&
        Objects.equals(this.tagFilter, immutableTagRule.tagFilter) &&
        Objects.equals(this.enabled, immutableTagRule.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, projectId, tagFilter, enabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImmutableTagRule {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    tagFilter: ").append(toIndentedString(tagFilter)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }


  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

