/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package run.acloud.commons.client.harbor.v1.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;


@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-08T09:10:54.107Z")
public class Manifest {
  @SerializedName("manifest")
  private Object manifest = null;

  @SerializedName("config")
  private String config = null;

  public Manifest manifest(Object manifest) {
    this.manifest = manifest;
    return this;
  }


  @Schema(description = "The detail of manifest.")
  public Object getManifest() {
    return manifest;
  }

  public void setManifest(Object manifest) {
    this.manifest = manifest;
  }

  public Manifest config(String config) {
    this.config = config;
    return this;
  }


  @Schema(description = "The config of the repository.")
  public String getConfig() {
    return config;
  }

  public void setConfig(String config) {
    this.config = config;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Manifest manifest = (Manifest) o;
    return Objects.equals(this.manifest, manifest.manifest) &&
        Objects.equals(this.config, manifest.config);
  }

  @Override
  public int hashCode() {
    return Objects.hash(manifest, config);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Manifest {\n");
    
    sb.append("    manifest: ").append(toIndentedString(manifest)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }


  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

