/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package run.acloud.commons.client.harbor.v1.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-08T09:10:54.107Z")
public class RobotAccountCreate {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("access")
  private List<RobotAccountAccess> access = null;

  public RobotAccountCreate name(String name) {
    this.name = name;
    return this;
  }


  @Schema(description = "The name of robot account")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RobotAccountCreate description(String description) {
    this.description = description;
    return this;
  }


  @Schema(description = "The description of robot account")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RobotAccountCreate access(List<RobotAccountAccess> access) {
    this.access = access;
    return this;
  }

  public RobotAccountCreate addAccessItem(RobotAccountAccess accessItem) {
    if (this.access == null) {
      this.access = new ArrayList<RobotAccountAccess>();
    }
    this.access.add(accessItem);
    return this;
  }


  @Schema(description = "The permission of robot account")
  public List<RobotAccountAccess> getAccess() {
    return access;
  }

  public void setAccess(List<RobotAccountAccess> access) {
    this.access = access;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RobotAccountCreate robotAccountCreate = (RobotAccountCreate) o;
    return Objects.equals(this.name, robotAccountCreate.name) &&
        Objects.equals(this.description, robotAccountCreate.description) &&
        Objects.equals(this.access, robotAccountCreate.access);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, access);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RobotAccountCreate {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("}");
    return sb.toString();
  }


  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

