/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package run.acloud.commons.client.harbor.v1.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;


@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-08T09:10:54.107Z")
public class ScannerRegistrationSettings {
  @SerializedName("name")
  private String name = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("auth")
  private String auth = "";

  @SerializedName("access_credential")
  private String accessCredential = null;

  public ScannerRegistrationSettings name(String name) {
    this.name = name;
    return this;
  }


  @Schema(example = "Clair", description = "The name of this registration")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ScannerRegistrationSettings url(String url) {
    this.url = url;
    return this;
  }


  @Schema(example = "http://harbor-scanner-clair:8080", description = "A base URL of the scanner adapter.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ScannerRegistrationSettings auth(String auth) {
    this.auth = auth;
    return this;
  }


  @Schema(description = "Specify what authentication approach is adopted for the HTTP communications. Supported types Basic', 'Bearer' and api key header 'X-ScannerAdapter-API-Key' ")
  public String getAuth() {
    return auth;
  }

  public void setAuth(String auth) {
    this.auth = auth;
  }

  public ScannerRegistrationSettings accessCredential(String accessCredential) {
    this.accessCredential = accessCredential;
    return this;
  }


  @Schema(example = "Bearer: JWTTOKENGOESHERE", description = "An optional value of the HTTP Authorization header sent with each request to the Scanner Adapter API. ")
  public String getAccessCredential() {
    return accessCredential;
  }

  public void setAccessCredential(String accessCredential) {
    this.accessCredential = accessCredential;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScannerRegistrationSettings scannerRegistrationSettings = (ScannerRegistrationSettings) o;
    return Objects.equals(this.name, scannerRegistrationSettings.name) &&
        Objects.equals(this.url, scannerRegistrationSettings.url) &&
        Objects.equals(this.auth, scannerRegistrationSettings.auth) &&
        Objects.equals(this.accessCredential, scannerRegistrationSettings.accessCredential);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, url, auth, accessCredential);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScannerRegistrationSettings {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    auth: ").append(toIndentedString(auth)).append("\n");
    sb.append("    accessCredential: ").append(toIndentedString(accessCredential)).append("\n");
    sb.append("}");
    return sb.toString();
  }


  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

