/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package run.acloud.commons.vo;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Permission
 */
@Schema(title="Harbor User Permission Model", description="Harbor User Permission Model")
public class HarborPermissionVO {
  @SerializedName("resource")
  private String resource = null;

  @SerializedName("action")
  private String action = null;

  public HarborPermissionVO resource(String resource) {
    this.resource = resource;
    return this;
  }

  /**
   * The permission resoruce
   * @return resource
   **/
  @Schema(description = "The permission resoruce")
  public String getResource() {
    return resource;
  }

  public void setResource(String resource) {
    this.resource = resource;
  }

  public HarborPermissionVO action(String action) {
    this.action = action;
    return this;
  }

  /**
   * The permission action
   * @return action
   **/
  @Schema(description = "The permission action")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HarborPermissionVO permission = (HarborPermissionVO) o;
    return Objects.equals(this.resource, permission.resource) &&
            Objects.equals(this.action, permission.action);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resource, action);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HarborPermissionVO {\n");

    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

